arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-spidev.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-spi4-m2-cs0-spidev.dts

add spi4-m2-cs0 spi0-m1-cs0 and fix spi0-m2-cs0

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3588-w1-gpio4-b1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-w1-gpio4-b2.dts

add rk3588 one wire example overlay

---

arch/arm64/boot/dts/rockchip/overlays/rk3568-i2c3-m0.dts

3b i2c : 
I2C3_M0
I2C2_M0
I2C1
,其他两个之前有添加

add radxa rock 3b i2c3-m0 support

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3568-can0-m0.dts

emm， 刚刚没注意还有个 can0-m0，这个也测试通过了的

Rock 3b can0

---

arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs1-spidev.dts

add radxa rock 3b spi3-cs1-m1 compatible support

---

arch/arm64/boot/dts/rockchip/overlays/rk3588-fiq-debugger-uart7m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-fiq-debugger-uart7m2.dts

fiq-debugger-uart7-m2 在5a 上可以，5b 不行

delete fiq-debugger-uart7 for the test failed

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-mcp2515-8mhz.dts

Signed-off-by: nascs <nascs@radxa.com>

add Radxa ROCK 4 mcp2515 support

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-enc28j60.dts

Enable enc28j60 on Radxa ROCK 4C+

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m2-cs0-mcp2515-8hmz.dts

add mcp2515 on spi0-m2 over cs0 for Radxa ROCK 5B

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rock-3a-radxa-5inch-touchscreen.dts

Since the power enable pin has changed, it can't be shared with the rock3b.

Add radxa 5inch TS for rock 3a

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm0-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm0-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm1-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm2-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm4.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm6.dts

以上 PWM 都验证通过， 还有 PWM7 PWM11_M1 PWM3 验证未通过，目前还在看具体怎么回事

Add Radxa CM3 Rpi CM4 PWM overlays

---

arch/arm64/boot/dts/rockchip/overlays/rk3568-can1-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-can1-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-i2c2-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-i2c3-m0.dts

Radxa ROCK 3A <= 1.2 complete

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c0-m2.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c1-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c1-m2.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c1-m4.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c7-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c7-m2.dts

add Radxa NX5 IO I2C support

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm11-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm3.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm7.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-spi0-m0-cs0-spidev.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-spidev.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-uart2-m0.dts

complete Radxa CM3 Rpi CM4 IO overlays

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm0-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm0-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm3.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm4.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-mcp2515.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-spidev.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs1-spidev.dts
arch/arm64/boot/dts/rockchip/overlays/rk3568-w1-gpio3-d1.dts

add Radxa CM3 IO overlays

---

arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-enc28j60.dts

rockchip-pinctrl pinctrl: pin gpio4-7 already requested by spi1.0; cannot claim for ff890000.i2s

change the interrupts pin

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rock-3a-raspberrypi-7inch-touchscreen.dts
arch/arm64/boot/dts/rockchip/overlays/rock-3b-raspberrypi-7inch-touchscreen.dts

The control pins of rock 3a and rock 3b vcc mipi are different.

split rock 3a and rock 3b rpi 7inch touchscreen

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-sodimm-io-radxa-display-8hd.dts
arch/arm64/boot/dts/rockchip/overlays/rock-3a-radxa-display-10hd.dts

rock3a: add radxa 10hd display cm3s: Fix node configuration error issue

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-radxa-display-10fhd.dts
arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-sodimm-io-radxa-display-10hd.dts
arch/arm64/boot/dts/rockchip/overlays/radxa-cm3i-io-radxa-display-10fhd.dts
arch/arm64/boot/dts/rockchip/overlays/radxa-cm3i-io-radxa-display-10hd.dts
arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-radxa-display-10fhd.dts
arch/arm64/boot/dts/rockchip/overlays/rock-3b-radxa-display-10fhd.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5a-radxa-display-10fhd.dts

add multiple products radxa 10fhd display,include rock 5a, rock 3b, radxa cm5 io, radxa cm3 io, radxa cm3s io, radxa cm3i io
Signed-off-by: lsj123lsjlsj <lisongjun@radxa.com>

adapt 10fhd display

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare25.dts
arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts

桌面版的需要[配置 X11](https://wiki.radxa.com/Rockpi4/hardware/display)

add waveshare 3.5 inch Display

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-enable-sharp-lq133t1jw01-edp-lcd-disable-dp1.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-radxa-camera-4k-on-cam0.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-radxa-camera-4k-on-cam1.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-radxa-display-8hd-on-lcd0.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-radxa-display-8hd-on-lcd1.dts

add some overlays for rock 5 itx
1.add edp lcd for rock 5 itx
2.add radxa display 8hd for rock 5 itx
3.add radxa 4k camera for rock 5 itx

add some overlays for rock 5 itx

---

arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-rpi-cm4-camera-v2-imx219-cam1.dts
arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-rpi-cm4-io-raspi-7inch-ts-disp1.dts

Because hardware swap device on i2c5 to i2c7.

change i2c5m3 to i2c7m2 for disp1 and cam1

---

arch/arm64/boot/dts/rockchip/overlays/rock-5a-radxa-camera-4k.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5a-radxa-display-10hd.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5a-radxa-display-8hd.dts

1. radxa camera 4k
2. radxa 10hd
3. radxa 8hd

Compatible with rock 5c

---

arch/arm64/boot/dts/amlogic/overlays/Makefile
arch/arm64/boot/dts/amlogic/overlays/meson-g12-disable-gpu.dts
arch/arm64/boot/dts/amlogic/overlays/meson-g12-disable-hdmi.dts
arch/arm64/boot/dts/amlogic/overlays/meson-g12-disable-usb.dts

Radxa zero

---

arch/arm64/boot/dts/amlogic/overlays/radxa-zero2-radxa-25w-poe.dts
arch/arm64/boot/dts/rockchip/overlays/rk3399-radxa-25w-poe.dts
arch/arm64/boot/dts/rockchip/overlays/rock-3a-radxa-25w-poe.dts
arch/arm64/boot/dts/rockchip/overlays/rock-3a-v12-radxa-25w-poe.dts
arch/arm64/boot/dts/rockchip/overlays/rock-3b-radxa-25w-poe.dts
arch/arm64/boot/dts/rockchip/overlays/rock-3c-radxa-25w-poe.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5a-radxa-25w-poe.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5b-radxa-25w-poe.dts

fix: change Radxa 25W PoE HAT to Radxa 25W PoE+ HAT

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rock-4c-plus-radxa-display-10fhd.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-hdmi0-8k.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-hdmi1-8k.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-radxa-display-10fhd.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-radxa-display-10hd.dts
arch/arm64/boot/dts/rockchip/overlays/rock-5b-plus-radxa-display-8hd.dts

add some overlays for rock5b+ and rock4cplus:
rock-5b-plus-hdmi0-8k.dts
rock-5b-plus-hdmi1-8k.dts
rock-5b-plus-radxa-display-8hd.dts
rock-5b-plus-radxa-display-10fhd.dts
rock-5b-plus-radxa-display-10hd.dts
rock-4c-plus-radxa-display-10fhd.dts

add some overlays for rock5b+ and rock4cplus

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3528-dwc3-otg.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart1m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart3m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart3m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart7m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm0-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm3-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm4-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm5-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart0-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart1-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart3-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart3-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart7-m0.dts

rock 2a: add pwm and uart support
Signed-off-by: SongJun Li lisongjun@radxa.com

rock 2a: add pwm and uart support

---

arch/arm64/boot/dts/rockchip/overlays/rk3588-pwm10-m2.dts

radxa cm5 io: add pwm10-m2

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-mcp2515.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-spidev.dts

rock 2a: add spi0 support use cs1

rock 2a: add spi0 support use cs1

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-radxa-taco-pcie2x1.dts
arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-io-radxa-camera-8m.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-host.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-peripheral.dts

1.update rk3588 otg port compatible
2.cm5: add radxa camera 8m
3. add radxa-cm3-radxa-taco-pcie2x1

cm5: update otg port overlay

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart1m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart2m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart3m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart3m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart7m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c0-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c1-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm3-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm4-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm5-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm6-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-enc28j60.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-mcp2515.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart1-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart2-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart7-m0.dts

rock 2a: add more support and fix problems on some overlays

rock 2a: add more support and fix problems on some overlays

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve.dts

rock 2a: add tve support and close hdmi

rock 2a: add tve support and close hdmi

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3528-dwc3-host.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-dwc3-otg.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-dwc3-peripheral.dts

rock 2a: add usb more support and modify otg compatible to unknown

rock 2a: add usb more support and modify otg compatible to unknown

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-waveshare35.dts

Signed-off-by: Peiyu Wu <wupeiyu@radxa.com>

rock 3c: add waveshare35 support

---

arch/arm64/boot/dts/rockchip/overlays/rk3568-i2c3-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rock-3c-raspberrypi-7inch-touchscreen.dts

rock 3c: add exclusive for i2c3

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/medge-rk3528a-io-enable-pcie.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-dwc3-host.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-dwc3-otg.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-dwc3-peripheral.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-enable-tve.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart1m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart2m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-fiq-debugger-uart3m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c0-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-i2c1-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm0-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm3-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm4-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-pwm6-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-enc28j60.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-mcp2515.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-spi0-cs1-spidev.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart0-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart1-m0.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart2-m1.dts
arch/arm64/boot/dts/rockchip/overlays/rk3528-uart3-m0.dts

feat: add medge-rk3528a io board to the overlays of the rk3528 series

feat: add medge-rk3528a io board to the overlays of the rk3528 series

---

arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-host.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-peripheral.dts

cm5io: add dwc3 host and devices support

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s2-2ch-m1-hifiberry-dac.dts
arch/arm64/boot/dts/rockchip/overlays/rk3588-i2s2-2ch-m1.dts

* 依赖 https://github.com/radxa-repo/bsp/pull/109

feat: rk3588: add two i2s2 sound card

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3568-hdmi-disable.dts
arch/arm64/boot/dts/rockchip/overlays/rockchip-gpu-disable.dts

Meets the low-power requirements of some users

feat: add rk3568-gpu/hdmi-disable.dts

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rock-3ab-max98357a.dts

Request:
* https://github.com/radxa-repo/bsp/pull/124

feat: add rock-3ab-max98357a

---

arch/arm64/boot/dts/rockchip/overlays/Makefile
arch/arm64/boot/dts/rockchip/overlays/rk3588-enable-sfc.dts

feat: add rk3588-sfc-enable and rk3588-sdhci-disable

---

arch/arm64/boot/dts/allwinner/overlays/cubie-a5e-radxa-display-8hd.dts
arch/arm64/boot/dts/allwinner/overlays/cubie-a7a-radxa-display-8hd.dts

fix: allwinner: change goodix driver

---

arch/arm64/boot/dts/allwinner/overlays/cubie-a7a-radxa-camera-8m-219.dts

fixes: https://applink.feishu.cn/client/message/link/open?token=Amg1LdbywUACaLFpdb2NABw%3D

fix: cubie-a7a-radxa-camera-8m-219: set to right isp pipeline
