radxa-pkg/radxa-overlays

arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c7-m3.dts
delete rock-5a and rock-5b compatible support, for the i2c7 channel is occupied by i2c7-m0
=> delete rock-5a and rock-5b compatible support

arch/arm64/boot/dts/rockchip/overlays/rk3588-uart2-m0.dts
使用uart2-m0, 需要手动删除 /boot/extlinux/extlinux.conf 里面的串口控制台相关的内容
"115200n8 console=ttyS2,1500000n8 console=ttyFIQ0,", description, 需要怎么写呢?
=> add radxa rock 5a and radxa rock 5b uart2-m0 support

arch/arm64/boot/dts/rockchip/overlays/rk3568-uart8-m1.dts
uart8-m1 无法使用，原因: uart8 的m0 通道被 bluetooth 占用， wiki 上已经删除了uart8-m1 的功能
=> delete uart8-m1 for the reason uart8-m0 conflicts with bt

arch/arm64/boot/dts/rockchip/overlays/rk3588-spi1-m1-cs1-mcp2515-8mhz.dts
我打开overlay 、接好线上电后，没有看到 can0 ,然后dmesg |grep spi 也有一堆报错，这个模块要不先删除，后面有时间再统一调一下吧?
=> delete mcp2515 on radxa rock 5b for the test failed

arch/arm64/boot/dts/rockchip/overlays/rk3588-uart2-m2.dts
可以禁用fiq，但是还有原uart2-m0串口打印， 但是不影响它作为普通通信串口使用
=> Fixed bug where fiq could not be disabled for uart2-m2

arch/arm64/boot/dts/amlogic/overlays/meson-g12-spi-b-mcp2515-8mhz.dts
=> delete Radxa Zero2 compatible support for mcp2515

arch/arm64/boot/dts/rockchip/overlays/radxa-cm3s-io-csi0-rpi-camera-v2.dts, arch/arm64/boot/dts/rockchip/overlays/radxa-cm3s-io-csi1-rpi-camera-v2.dts
The original control method is invalid in the 5.10 kernel driver, and the regulator is used to realize it.
=> cm3s io: camera v2: Modify the control method of pwdn_gpio

arch/arm64/boot/dts/rockchip/overlays/rk3568-i2c3-m0.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-i2c4-m0.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm12-m1.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm13-m1.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm14-m0.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm14-m1.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm15-m1.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm8-m0.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm9-m0.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-enc28j60.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-mcp2515.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m1-cs0-spidev.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-uart2-m0.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-uart3-m0.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-uart4-m1.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-uart5-m1.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-uart9-m1.dts
Radxa Zero 3W 和 Radxa ROCK 3C 的 40 pin 一致
=> Add Radxa Zero 3W overlays support

arch/arm64/boot/dts/amlogic/overlays/meson-g12-pwm-b-h.dts, arch/arm64/boot/dts/amlogic/overlays/meson-g12-pwm-b-z.dts
CONFIG_PWM_MESON=m, 这个驱动没开
其他几个还不知道什么原因
=> open Radxa Zero2 pwm_b overlays

arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-i2c0-hym8563.dts, arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-pcie2x1.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm0-m0.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-pwm0-m1.dts
pwm0 is used by the fan， hym8563 rtc device integrated on the CM3IO base board.
=> cm3 io: disable pwm0, set hym8563 overlay to unknown,fix pcie overlay.

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rk3399-pwm-ir-remotectl.dts, arch/arm64/boot/dts/rockchip/overlays/rk3399-pwm1-ir-rx.dts
遥控器是 car mp3, 和[这款](https://gist.github.com/danyboy666/f342c1cca26e88e0e637ee071698ac56)样式一样，但是目前还有两个按键没有适配(100+ 200+), 一是找不到定义，二是自己定义一个不生效
=> add carMp3 pwm ir remotectl for rock4

arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-mcp2515-8mhz.dts
rockchip,pins = <4 29 0 &pcfg_pull_none>;
中断脚当时写错了，bank 4 的第 29 个 pin 是 GPIO4_D5
=> fix the description of rk3399-spi1-mcp2515-8mhz

arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-jedec-nor.dts, arch/arm64/boot/dts/rockchip/overlays/rk3399-spi2-jedec-nor.dts
Excessive speed rates may result in written data
not matching the actual data.
=> rockchip: rk3399: Limit spi maximum rate

arch/arm64/boot/dts/rockchip/overlays/rk3588-spi2-m1-cs0-spidev.dts
log: 
[    6.740823] spi_master spi2: spi_device register error /spi@feb20000/rk806single@0
开了这个 overlay 系统会起不来
=> disable spi2, cs0 is occupied by rk806

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rk3328-pwm2.dts, arch/arm64/boot/dts/rockchip/overlays/rk3328-spi0-spidev.dts
1. The previous rk3328-pwm2.dts defines pwm0_pin incorrectly, change it to the correct pwm2_pin.
2. Changed the compatible attribute of rk3328-spi0-spidev.dts to "armbian,spi-dev" to match the spidev driver of the upstream kernel.
3. Added dtbo to Makefile to compile rk3328 overlay.
=> Modify the overlay of rk3328-rock-pi-e.

arch/arm64/boot/dts/rockchip/overlays/rk3308-i2c3-m0.dts, arch/arm64/boot/dts/rockchip/overlays/rk3308-pwm2.dts, arch/arm64/boot/dts/rockchip/overlays/rk3308-pwm3.dts
Reasons for changes to  i2c3-m0 : The level of the enable output is only 0.23V, pcfg_pull_up_12ma is added to raise the level to 3.3 V.
Reasons for changes to  pwm2 / pwm3 :  Changed the pinctrl-names from `acticve` to `default`, and also raised the output voltage to 3.3 V.
=> Modified the overlay of rk3308 i2c3-m0 ,pwm2, pwm3.

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rk3328-uart2-m1.dts
Fixed previous error, rk3328 uart2 uses uart2m1_xfer pin. The reason for the change from compatible to unknow is that uart2 is already turned on in rock-pi-e.dts.
=> rk3328: Changed Makefile and changed uart2-m0 to uart2-m1.

arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-radxa-camera-8m-cam1.dts, arch/arm64/boot/dts/rockchip/overlays/radxa-cm3-io-radxa-camera-8m-cam2.dts, arch/arm64/boot/dts/rockchip/overlays/radxa-cm3i-io-radxa-camera-8m-cam1.dts, arch/arm64/boot/dts/rockchip/overlays/radxa-cm3i-io-radxa-camera-8m-cam2.dts, arch/arm64/boot/dts/rockchip/overlays/radxa-cm3s-io-csi0-radxa-camera-8m.dts, arch/arm64/boot/dts/rockchip/overlays/radxa-cm3s-io-csi1-radxa-camera-8m.dts, arch/arm64/boot/dts/rockchip/overlays/rock-3ab-radxa-camera-8m.dts, arch/arm64/boot/dts/rockchip/overlays/rock-3c-radxa-camera-8m.dts, arch/arm64/boot/dts/rockchip/overlays/rock-4-radxa-camera-8m.dts
Since the name of the camera was changed from Radxa Camera 8M to Radxa Camera 8M 219, the title and description in the overlay associated with it have to be changed.
=> Change title and description to Radxa Camera 8M 219

arch/arm64/boot/dts/rockchip/overlays/rk3588-dwc3-otg.dts
dr_mode is set to otg by kernel.
=> rk3588: remove otg mode overlay

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-waveshare35.dts, arch/arm64/boot/dts/rockchip/overlays/rk3568-spi3-m0-cs0-waveshare35.dts, arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-waveshare35.dts
Signed-off-by: Nascs Fang <nascs@radxa.com>
=> add waveshare spi lcd support

arch/arm64/boot/dts/amlogic/overlays/Makefile, arch/arm64/boot/dts/amlogic/overlays/amlogic-g12-watchdog.dts, arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rockchip-watchdog.dts
Signed-off-by: Nascs Fang <nascs@radxa.com>
rk3399, 用的是 4C+ 做的测试， rk356x 用的是 CM3-IO， rk3588 用的是 5B
=> rockchip: add watch dog support

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-enable-sharp-lq133t1jw01-edp-lcd-disable-dp0.dts, arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-enable-sharp-lq133t1jw01-edp-lcd-disable-dp1.dts, arch/arm64/boot/dts/rockchip/overlays/rock-5-itx-hdmi1-8k.dts
1.close rock-5-itx-enable-sharp-lq133t1jw01-edp-lcd-disable-dp1 overlay
The hdmiphyclk0 used by dp0 on the software is in conflict with edp0, so disable the dual-display function of edp0 and dp0.
2.add rock-5-itx-enable-sharp-lq133t1jw01-edp-lcd-disable-dp0 overlay
=> update overlay for rock5itx

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rock-2a-eeprom.dts
rock 2a: add eeprom support on i2c1-m0
=> rock 2a: add eeprom support on i2c1-m0

arch/arm64/boot/dts/rockchip/overlays/rk3588-spi0-m1-cs0-mcp2515-8mhz.dts
Modified the description of the INT pin because rock-5a ,rock-5c and cm5 use different INT pins. rock-5a and rock-5c : pin27
cm5-io: pin31
=> fix: rk3588-spi0-m1-cs0-mcp2515-8mhz.dts

.github/workflows/build.yml, arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/Makefile.rk3588-can, debian/rules
* closes https://github.com/radxa-pkg/radxa-overlays/issues/316
=> fix: can overlays aren't compiled when kernel is bsp 6.1

arch/arm64/boot/dts/rockchip/overlays/rk3588-i2c1-m0.dts
Conflicts with pmu i2c when used on ROCK5B/ROCK5B+.
=> overlays: disable i2c1-m0 for ROCK5B/ROCK5B+

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rockchip-uart-dma.dts
* closes https://github.com/radxa-pkg/radxa-overlays/issues/366
RK3399 没有定义 dmas 属性
RK33*8 默认开启dma
内核串口驱动默认配置，会导致rx dma触发cpu中断，所以不开
=> feat: add rockchip-uart-tx-dma

arch/arm64/boot/dts/rockchip/overlays/rk3568-i2c5-m0.dts
Testing different overlays on my Zero3W and noticed I2C5 works too. If this was left out for a reason, please ignore.
=> Add zero3 to rk3568-i2c5-m0.dts

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rk3308-pdm-m2.dts
目前有点失真，勉强能用，盲猜是频率问题。测试用的mic datasheet说明最大频率为4M,实际测试为5M，尝试使用
```
assigned-clocks = <&cru SCLK_PDM>, <&cru HCLK_PDM>;
assigned-clock-rates = <400000>, <400000>;
```
控制无效
=> feat: add overlay rk3308-pdm-m2

arch/arm64/boot/dts/amlogic/overlays/Makefile, arch/arm64/boot/dts/amlogic/overlays/radxa-zero-spi-b-waveshare35b.dts
微雪mhs3.5屏幕
使用官方radxa-zero_debian_bullseye_cli_b23.img 镜像
内核需要添加ads7846触屏驱动
B-spi
显示屏 ：ili9486
LCD_RS （PIN18:DC）			    DC引脚        （PIN18：GPIOX_8）
RST    （PIN22：RESET）			 RESET引脚    （PIN7：GPIOAO_3）
LCD_SI （PIN19：MOSI）   		 MOSI引脚     （PIN19：GPIOH_4）
LCD_SCK（PIN23：SCLK）			 SCLK引脚     （PIN23：GPIOH_7）
LCD_CS （PING24：SS）			 SS引脚		   （PIN24：GPIOH_6）
触屏：ads7846：xpt2046
TP_IRQ  （PIN11：GPIOAO_2）           PIN11
TP_SI   （PIN19：GPIOH_4）            PIN19
TP_SO   （PIN21：GPIOH_5）            PIN21
TP_SCK  （PIN23：GPIOH_7）            PIN23
TP_CS   （PIN26：GPIOX_9）          	PIN12
=> Radxa zero 使用 微雪spi 3.5

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/rk3399-spi1-cs-gpio-slb9670.dts
This update introduces support for the Infineon SLB9670 Trusted Platform Module (TPM), which provides secure key storage and hardware random number generation (HWRNG). The implementation enables the TPM on the `spi1` bus with `CS1` using a GPIO pin for RK3399-based systems, potentially extensible to other boards.
- Added the `rk3399-spi1-add-cs1.dts` overlay to support multi-CS configuration on SPI1 (**CS0 is used by the SPI-flash on some boards**)
- Introduced the `tpm-slb9670.dts` overlay to configure and activate the SLB9670 TPM using the new available CS1.
The TPM functionality on SPI has been verified on a RockPi 4C using a GeeekPi TPM9670 Module ([EP-0149](https://wiki.52pi.com/index.php/EP-0149)) from [52pi.com](52pi.com), initially designed for the Raspberry Pi header.
**Note:** …
=> Add support for TPM SLB9670 module on RK3399 platform

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/radxa-zero3-walnutpi154-lcd.dts, arch/arm64/boot/dts/rockchip/overlays/radxa-zero3-waveshare13-lcd-hat.dts
Add Walnut Pi 1.54-inch LCD overlay and Waveshare 1.3-inch LCD HAT overlay.
I am very sorry for the blunder I made in [[#412 ](https://github.com/radxa-pkg/radxa-overlays/pull/412)].
=> Add screen overlays

arch/arm64/boot/dts/rockchip/overlays/Makefile, arch/arm64/boot/dts/rockchip/overlays/radxa-cm5-rpi-cm4-io-deskpi-mini-cube.dts
Working:
- USB Type-A (both ports)
- HDMI 1 (furthest from USB Type-C receptacle)
- RJ-45 Gigabit Ethernet
- Fan PWM (GPIO0_B5)
- LEDs
Not working:
- HDMI 2 (closest to USB Type-C receptacle) due to only 1x HDMI interface on Radxa CM5
- Maskrom mode
Fixes radxa-pkg/radxa-overlays#420.
=> feat: Add support for DeskPi Mini Cube for Radxa CM5 (radxa,cm5-rpi-cm4-io)

arch/arm64/boot/dts/rockchip/overlays/rk3576-dwc3-host.dts
The OTG port on the Radxa CM4-IO can automatically switch between host and device modes. Disable this feature to resolve the issue where devices cannot be recognized after switching to host mode.
=> feat: remove otg host mode support for radxa-cm4-io

arch/arm64/boot/dts/allwinner/overlays/cubie-a5e-radxa-camera-8m-219.dts
and enhance the frequency of CSI and ISP
To fix the issue of being unable to capture YUV format due to images not being processed by the ISP
fixes: https://aservice.allwinnertech.com/issues/90230
=> fix: cubie-a5e-radxa-camera-8m-219: set to right isp pipeline
